[package]
name = "svc-keys"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dashmap = "5.4"
rand = "0.8"
base64 = "0.21"
colored = "2.0"
